### PR TITLE
Notifications

### PR DESCRIPTION
**Pull request by michaelhall923**
- add notifications page
- change useProfile to useUser/useUsers

### CODE REVIEW

**Comment by michaelhall923** [comment]
Seems like this added more flickering lol. I've noticed the flickering happens whenever `events` changes. Haven't figured out the solution though.

**Comment by SamSamskies** [comment]
I haven't noticed flickering since I added caching. I'll review this PR tomorrow to see if I can figure out what's causing it. I think we need ghost loading states on initial load. That will probably solve the problem. Snort has a basic example of that where initial feed load always displays ghost loading notes for a short period of time before rendering the actual feed. One pattern for ghost loading states is to always render it for a short period of time like 300 ms even if fetching the data happens faster than that.

We should also think about using `ndk.fetchEvents` for initial loading of feeds. That way the number of events don't change while loading. We'd get all the data and then render the feed once on initial load. A subscription could be loaded after in the background and we could display a bubble at the top that there's new events to be rendered. I think most clients use this pattern.

Primal's notification screen looks like this when notifications roll in. So on initial load all events are fetched and then after that a bubble displays at the top if more notifications are detected. This way the screen doesn't go crazy if something you post goes viral.
Screenshot 2023-06-11 at 3 16 34 PM

**Comment by SamSamskies** [comment]
@rockymedure do you wanna functionally test this update? I haven't posted anything on Stemstr yet, so I have nothing on my notifications screen.

**Comment by michaelhall923** [comment]
Sounds good. I'm just gonna go ahead and merge this so I can move forward with other stuff.

**Comment by michaelhall923** [comment]
The comment/likes counts are flickering for me on the current build main build.

This notifications update causes the note headers to flicker too. Guessing it has something to do with the useUsers hook I addedd.

**Comment by michaelhall923** [comment]
Also noticed flickering doesn't happen in threads

**Comment by michaelhall923** [comment]
@SamSamskies I just realized the flickering only happens on notes created by the logged in user

**Comment by SamSamskies** [comment]
> @SamSamskies I just realized the flickering only happens on notes created by the logged in user

Maybe that's why I don't see it. I don't have any notes on Stemstr. 😂

**Pull request merged**
