### PR TITLE
click title to scroll to top of feed

### PR DESCRIPTION
**Pull request by michaelhall923**
wonder if there's a more elegant way to do this. feels hacky.

### CODE REVIEW

**Comment by SamSamskies** [comment]
yeah i think there's an easier way. let me try play around with it.

**Comment by SamSamskies** [comment]
the only thing i can think of to clean it up a little is to make a `VariableSizeListRefProvider`. that way you don't need to prop drill the `listRef`. or maybe you could just call the the provider `FeedProvider`.

**Comment by michaelhall923** [comment]
Yeah i was thinking about a FeedProvider. might do that

**Comment by SamSamskies** [comment]
maybe you should just forget about scrolling to the top and just refresh the page when they click stemstr. that would solve the problem with not being able to load new content without hard closing the app with the pwa.

**Comment by michaelhall923** [comment]
> maybe you should just forget about scrolling to the top and just refresh the page when they click stemstr. that would solve the problem with not being able to load new content without hard closing the app with the pwa.

true!

**Pull request closed without merging**
