### PR TITLE
add 48px to bottom of comment sheet

### PR DESCRIPTION
**Pull request by SamSamskies**
resolves https://github.com/stemstr/Client/issues/171

### CODE REVIEW

**Comment by michaelhall923** [comment]
I made this hasNotch function if you want to do this conditionally. I have no idea if it works.

```
import { isIOS } from "react-device-detect";

export function hasNotch() {
  const screenWidth = window.screen.width;
  const screenHeight = window.screen.height;

  // Define common notch aspect ratios (as of September 2021)
  const notchAspectRatios = [
    { width: 1125, height: 2436 }, // iPhone X, XS, 11 Pro
    { width: 1242, height: 2688 }, // iPhone XS Max, 11 Pro Max
    { width: 828, height: 1792 }, // iPhone XR, 11
    { width: 1170, height: 2532 }, // iPhone 12, 13 mini
    { width: 1284, height: 2778 }, // iPhone 12 Pro Max, 13 Pro Max
  ];

  return (
    notchAspectRatios.some(
      (aspectRatio) =>
        screenWidth === aspectRatio.width && screenHeight === aspectRatio.height
    ) && isIOS
  );
}
```

**Review by bndw — APPROVED** [review]

**Comment by SamSamskies** [comment]
> 

so we only want to add the padding if there's a notch on the bottom? the issue doesn't specify that.

also, i have an iPhone XR and the notch only shows when viewing as a PWA. are you sure the notch shows for regular websites in a browser?

**Comment by SamSamskies** [comment]
i meant the notch only show on our navbar when viewed as a PWA. in the browser the notch is on the browser navbar.

**Comment by rockymedure** [comment]
That's correct!

**Comment by SamSamskies** [comment]
hmmmm it's borked. let me play around with it some more.

**Comment by SamSamskies** [comment]
k should be good now.

**Comment by bndw** [comment]
LGTM

image

**Comment by SamSamskies** [comment]
> 

wrong PR 😂. this one is for the comment sheet.

**Comment by michaelhall923** [comment]
Yeah so on an iPhone SE (no notch) in a PWA, this would make the padding uneven

**Comment by michaelhall923** [comment]
also do any androids have the tab thingy?

**Comment by SamSamskies** [comment]
> 

oh so combine your function result with my isPWA result to figure out whether to increase the bottom nav? or should we just keep it simple like bluesky and always increase the bottom padding for PWAs?

**Comment by SamSamskies** [comment]
> also do any androids have the tab thingy?

i have no idea.

**Comment by michaelhall923** [comment]
> oh so combine your function result with my isPWA result to figure out whether to increase the bottom nav

yeah. should only increase the height if both isPWA and hasNotch are true

**Comment by SamSamskies** [comment]
i think all your numbers are double what they supposed to be. gonna em all in half.

**Comment by michaelhall923** [comment]
that was chatgpt haha def don't take it at face value

**Comment by SamSamskies** [comment]
actually there's a formula to calculate the viewport sizes.

**Comment by SamSamskies** [comment]
> that was chatgpt haha def don't take it at face value

mf chatgpt 😂

**Comment by SamSamskies** [comment]
i just plopped the numbers into chatgpt and told it to fix it and it looks good now 😂

**Pull request merged**
